### ISSUE TITLE
ARM64 build

### ISSUE THREAD

**Issue by ymontmarin** [conda-forge/libuwebsockets-feedstock#10]
### Comment:

Hi everyone,

Would it be possible to make this recipe build a package version for the ARM64 platform? Having tested it on an Apple M1 laptop, the build.sh should work as it is.

Thank you in advance. Related to https://github.com/conda-forge/libusockets-feedstock/issues/5

If you tell me how to activate an ARM64 on a recipe I can propose a PR.

ymm

**Comment by traversaro** [comment]
See https://conda-forge.org/docs/maintainer/knowledge_base.html#apple-silicon-builds . In a nutshell, you need to add `libuwebsockets` to https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/migrations/osx_arm64.txt via a pull request (see for example https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/2995 or https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/3033), then `libuwebsockets` and all its dependencies will be added to the osx_arm64 migrator in https://conda-forge.org/status/#armosxaddition . As the dependencies are automatically added, this will automatically also handle https://github.com/conda-forge/libusockets-feedstock/issues/5 .

It is also possible to add the osx_arm64 support manually to the repo, but the manual way is a bit more tricky.

**Comment by traversaro** [comment]
Fixed by https://github.com/conda-forge/libuwebsockets-feedstock/pull/11, thanks @ymontmarin for https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/4635 .
